import portfolio as P, os
ALL = "BTC-USD,ETH-USD,SOL-USD,ADA-USD,DOGE-USD,LINK-USD,AVAX-USD,DOT-USD,LTC-USD,ATOM-USD,BCH-USD,ETC-USD,XLM-USD,XTZ-USD,ALGO-USD,UNI-USD,FIL-USD,AAVE-USD,XRP-USD,ICP-USD,NEAR-USD,APT-USD".split(",")
NEW16 = "ZRX-USD,BAT-USD,ZEC-USD,EOS-USD,DASH-USD,OMG-USD,KNC-USD,COMP-USD,MKR-USD,SNX-USD,YFI-USD,GRT-USD,CRV-USD,MANA-USD,SAND-USD,AXS-USD".split(",")
base = dict(long_only=True, K=20, r3_vt=0.30)
D = P.prepare(ALL)
print("== M9 on 22 coins: yield assumption ==")
for y in (0.0, 0.02, 0.04): P.row(f"M9 yield {y*100:.0f}%", P.simulate(D, **base, cash_yield=y))
print("== M9 on 22 coins: round-trip cost ==")
for c in (0.0006, 0.0015, 0.0030): P.row(f"M9 cost {c*100:.2f}%", P.simulate(D, **base, cost=c))
print("== M9 on 22 coins: execution delay ==")
for d in (0, 1, 2): P.row(f"M9 delay {d}h", P.simulate(D, **base, delay=d))
print("== M9 on 22 coins: mix plateau (trend vol target x dip slots) ==")
for vt in (0.25, 0.30, 0.35):
    for K in (15, 20, 25): P.row(f"vt{int(vt*100)} K={K}", P.simulate(D, long_only=True, K=K, r3_vt=vt))
print("== 16 coins never used in any selection (ZRX ... AXS), same fixed configs ==")
D16 = P.prepare(NEW16); print("coins:", D16["coins"])
P.row("M9 vt30 K=20 long-only", P.simulate(D16, **base))
P.row("M10 vt30 K=15 long-only", P.simulate(D16, long_only=True, K=15, r3_vt=0.30))
P.row("R3 vt30 only", P.simulate(D16, K=0, r3_vt=0.30))
P.row("B* K=20 long-only only", P.simulate(D16, use_r3=False, long_only=True, K=20))
P.row("buy&hold-ish: R3 vt99 long-only", P.simulate(D16, K=0, r3_vt=9.9))
